# Form implementation generated from reading ui file 'expressionToolGUI.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6.QtGui import QPixmap
from PyQt6 import QtCore, QtGui, QtWidgets
import cv2
from cv2_enumerate_cameras import enumerate_cameras

POSSIBLE_EMOTIONS = ['happy', 'sad', 'neutral', 'surprise', 'angry', 'fearful', 'disgust']
class Ui_MainWindow(object):
    def __init__(self):
        self.emotion_image_paths = {emotion: '' for emotion in POSSIBLE_EMOTIONS}
        self.emotion_radio_buttons = {emotion: None for emotion in POSSIBLE_EMOTIONS}
        self.emotion_textline_inputs = {emotion: None for emotion in POSSIBLE_EMOTIONS}
        self.current_toggled_emotion = POSSIBLE_EMOTIONS[0]

    def getEmotionImageToggleAction(self, select_emotion: str):
        def emotionImageToggleAction():
            previous_toggled_emotion = self.current_toggled_emotion
            self.current_toggled_emotion = select_emotion
            if previous_toggled_emotion in self.emotion_textline_inputs:
                self.emotion_textline_inputs[previous_toggled_emotion].setDisabled(True)
            if self.current_toggled_emotion in self.emotion_textline_inputs:
                self.emotion_textline_inputs[self.current_toggled_emotion].setDisabled(False)
        return emotionImageToggleAction

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(495, 370)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.ioVerticalLayout = QtWidgets.QVBoxLayout()

        self.inputVerticalLayout = QtWidgets.QVBoxLayout()
        self.inputVerticalLayout.setObjectName("inputVerticalLayout")

        self.webcamHorizontalLayout = QtWidgets.QHBoxLayout()

        self.inputButtonGroup = QtWidgets.QButtonGroup(self.inputVerticalLayout)

        self.webcamInputBtn = QtWidgets.QRadioButton('Webcam Input')
        self.webcamInputBtn.setChecked(True)
        self.inputButtonGroup.addButton(self.webcamInputBtn)
        self.webcamHorizontalLayout.addWidget(self.webcamInputBtn)
        
        self.webcamCombo = QtWidgets.QComboBox()
        self.webcamHorizontalLayout.addWidget(self.webcamCombo)
        self.inputVerticalLayout.addLayout(self.webcamHorizontalLayout)

        self.obsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.obsInputBtn = QtWidgets.QRadioButton('OBS Input')
        self.obsInputBtn.setChecked(False)
        self.inputButtonGroup.addButton(self.obsInputBtn)
        self.obsHorizontalLayout.addWidget(self.obsInputBtn)

        self.obsInputEdit = QtWidgets.QLineEdit('expressionToolSource')
        self.obsHorizontalLayout.addWidget(self.obsInputEdit)
        self.inputVerticalLayout.addLayout(self.obsHorizontalLayout)

        self.hotkeyInputBtn = QtWidgets.QRadioButton('Hotkey Input')
        self.hotkeyInputBtn.setChecked(False)

        self.inputVerticalLayout.addWidget(self.hotkeyInputBtn)
        self.inputButtonGroup.addButton(self.hotkeyInputBtn)

        self.ioVerticalLayout.addLayout(self.inputVerticalLayout)

        self.outputVerticalLayout = QtWidgets.QVBoxLayout()
        self.outputVerticalLayout.setObjectName('outputVerticalLayout')
        self.outputBtnGroup = QtWidgets.QButtonGroup(self.outputVerticalLayout)

        self.windowOutputBtn = QtWidgets.QRadioButton('Window Output')
        self.outputVerticalLayout.addWidget(self.windowOutputBtn)
        self.windowOutputBtn.setChecked(True)
        self.outputBtnGroup.addButton(self.windowOutputBtn)

        self.obsOutputHorizontalLayout = QtWidgets.QHBoxLayout()
        self.obsOutputBtn = QtWidgets.QRadioButton('OBS')
        self.obsOutputBtn.setChecked(False)
        self.obsOutputEdit = QtWidgets.QLineEdit('expressionToolSource')
        self.obsOutputHorizontalLayout.addWidget(self.obsOutputBtn)
        self.obsOutputHorizontalLayout.addWidget(self.obsOutputEdit)
        self.outputBtnGroup.addButton(self.obsOutputBtn)
        self.outputVerticalLayout.addLayout(self.obsOutputHorizontalLayout)

        self.webserverOutputBtn = QtWidgets.QRadioButton('Webpage Output')
        self.webserverOutputBtn.setChecked(False)
        self.outputVerticalLayout.addWidget(self.webserverOutputBtn)
        self.outputBtnGroup.addButton(self.webserverOutputBtn)

        self.hotkeyOutputBtn = QtWidgets.QRadioButton('Hotkey Output')
        self.hotkeyOutputBtn.setChecked(False)
        self.outputVerticalLayout.addWidget(self.hotkeyOutputBtn)
        self.outputBtnGroup.addButton(self.hotkeyOutputBtn)

        self.ioVerticalLayout.addLayout(self.outputVerticalLayout)

        self.emotionVerticalLayout = QtWidgets.QVBoxLayout()
        self.emotionSelectButton = QtWidgets.QButtonGroup(self.emotionVerticalLayout)
        self.emotionPath = {}
        for emotion in POSSIBLE_EMOTIONS:
            emotionHorizontalLayout = QtWidgets.QHBoxLayout()
            emotionSelectBtn = QtWidgets.QRadioButton(emotion+' Image File Path')
            emotionSelectBtn.toggled.connect(self.getEmotionImageToggleAction(emotion))
            self.emotionSelectButton.addButton(emotionSelectBtn)
            emotionPathEdit = QtWidgets.QLineEdit('')
            emotionHorizontalLayout.addWidget(emotionSelectBtn)
            emotionHorizontalLayout.addWidget(emotionPathEdit)
            self.emotion_radio_buttons[emotion] = emotionSelectBtn
            self.emotion_textline_inputs[emotion] = emotionPathEdit
            self.emotionVerticalLayout.addLayout(emotionHorizontalLayout)

        self.emotion_radio_buttons[POSSIBLE_EMOTIONS[0]].setChecked(True)

        self.ioVerticalLayout.addLayout(self.emotionVerticalLayout)

        self.listWidget_2 = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget_2.setObjectName("listWidget_2")
        # self.verticalLayout_2.addWidget(self.listWidget_2)
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        # self.verticalLayout_2.addWidget(self.listWidget)
        self.imageLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.imageLabel.setObjectName("imageLabel")
        self.imageLabel.setFixedSize(600, 600)
        # self.imageLabel.setScaledContents(True)
        self.horizontalLayout.addLayout(self.ioVerticalLayout)
        self.horizontalLayout.addWidget(self.imageLabel)
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton = QtWidgets.QPushButton('Launch', parent=self.centralwidget)
        self.pushButton.setObjectName("Launch")
        self.pushButton.clicked.connect(self.openFileDialog)

        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 495, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "expressionTool GUI"))
        self.pushButton.setText(_translate("MainWindow", "Launch"))

    def openFileDialog(self):
        print('openFileDialog')
        fileDialog = QtWidgets.QFileDialog()
        fileDialog.setWindowTitle('Open File')
        fileDialog.setFileMode(QtWidgets.QFileDialog.FileMode.ExistingFile)
        fileDialog.setViewMode(QtWidgets.QFileDialog.ViewMode.Detail)

        if fileDialog.exec():
            selectedFiles = fileDialog.selectedFiles()
            print('Selected File: ', selectedFiles[0])
            self.emotion_textline_inputs[self.current_toggled_emotion].setText(selectedFiles[0])
            self.emotion_image_paths[self.current_toggled_emotion] = selectedFiles[0]
            pixmap = QPixmap(selectedFiles[0])
            self.imageLabel.setPixmap(pixmap)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    pixmap = QPixmap('araragi2.jpg')
    scaled_pixmap = pixmap.scaled(
            ui.imageLabel.size(),
            QtCore.Qt.AspectRatioMode.KeepAspectRatio,
            QtCore.Qt.TransformationMode.SmoothTransformation
            )

    for camera_info in enumerate_cameras():
        print(f'{camera_info.index}   {camera_info.name}')
        ui.webcamCombo.addItem(f'{camera_info.index}   {camera_info.name}')
    
    ui.imageLabel.setPixmap(scaled_pixmap)
    MainWindow.show()
    sys.exit(app.exec())
